[tool.poetry]
name = "syslog-ng-cfg-helper"
version = "1.8.1"
description = "Configuration helper for syslog-ng."
authors = ["Attila Szakacs <szakacs.attila96@gmail.com>"]
readme = "README.md"
license = "GPL-3.0-only"
homepage = "https://github.com/syslog-ng/syslog-ng-cfg-helper"
repository = "https://github.com/syslog-ng/syslog-ng-cfg-helper"
keywords = ["syslog-ng", "configuration", "cfg"]
classifiers = [
    "Environment :: Console",
    "Operating System :: OS Independent",
    "Topic :: System :: Networking",
    "Topic :: System :: Systems Administration",
]
packages = [{include = "syslog_ng_cfg_helper"}]
include = [
    "LICENSE",
    "syslog_ng_cfg_helper/syslog-ng-cfg-helper.db",
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.group.dev.dependencies]
neologism = "^0.0.8"
pytest = "^8.3.4"
mypy = "^1.1.13"
black = "^24.3.0"
pylint = "^3.2.7"
pycodestyle = "^2.10.0"
pyright = "^1.1.394"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
exclude = "tests/module_loader/test_parse_driver.py"

[tool.poetry.scripts]
syslog-ng-cfg-helper = 'syslog_ng_cfg_helper.console:run'
